### ISSUE TITLE
Poster Plugin - not able to select items

### ISSUE THREAD

**Issue by tomadams** [omeka/plugin-Posters#14]
I was wondering if the Poster plugin on Github omeka/plugin-Posters is functional.

I installed the 5-day old version of the plugin Poster 0.1 on Omeka version 2.2 and when I attempt to "Add An Item", I see in the pop-up window a list of possible items and their thumbnails, by clicking on on an item will then display "Select Item =>"  and hovering over the "Select Item =>" does display the green drop shadow. However, when I click that button, It just goes back to the "Edit Poster", without any items appearing as being listed in the poster. Somehow my browser (Firefox 31.0), is not displaying (I am assuming a pop up) add form.

**Comment by zerocrates** [comment]
We let this sit around for so long that it's probably not useful any more, and I don't think we've gotten any other complaints of this same problem.

I'm closing this, but if this is still a problem for you, feel free to comment and we can reopen the issue.
