### ISSUE TITLE
Test tinymce4

### ISSUE THREAD

**Issue by zerocrates** [omeka/plugin-Posters#16]
core master, posters tinymce4

Editors appear on the admin configuration page for the plugin, and as the description entry for poster add/edit on the front side, as well as captions for each selected item.

omeka/omeka#837

**Comment by mebrett** [comment]
Formatted text for item captions looks fine in the editor but doesn't actually display. Lists show up as new lines, but bold/italics get stripped.

I think it might make more sense to leave the captions unformatted completely, and only allow wysiwyg on the poster description. 

Editor: 
![screen shot 2018-02-02 at 4 21 15 pm](https://user-images.githubusercontent.com/2314070/35755424-2f855f10-0835-11e8-8293-f6f3415507c5.png)

Display:
![screen shot 2018-02-02 at 4 21 42 pm](https://user-images.githubusercontent.com/2314070/35755431-358f689c-0835-11e8-9854-082c44544315.png)

**Comment by mebrett** [comment]
Looks fine on static - we can make a note in the documentation that formatted text may not display properly in carousel view.

**Comment by mebrett** [comment]
Non-carousel display shows all formatting on Firefox, Chrome, and Safari so I'd say this is a go.
